receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch: {}

exporters:
  azuremonitor:
    connection:
      instrumentation_key: ${AZURE_APPINSIGHTS_INSTRUMENTATION_KEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
